EXEMPLAR_P01 = (
    "REFERÊNCIA DE PROFUNDIDADE (use como guia de densidade, NÃO copie):\n\n"
    "## Visão do Produto\n"
    "| Atributo | Valor |\n"
    "|---|---|\n"
    "| Codinome interno | OmniPrice Next |\n"
    "| Versão atual | 0.1.0 (definida em package.json e pyproject.toml) |\n"
    "| Declaração de visão | Unificar ofertas de Shopee, Magalu, Amazon e Mercado Livre "
    "utilizando ISR para garantir SEO máximo e performance instantânea ao consumidor brasileiro. |\n\n"
    "## Problema e Solução\n"
    "| ID | Problema | Impacto | Como o Sistema Resolve |\n"
    "|---|---|---|---|\n"
    "| P-01 | APIs heterogêneas por marketplace (formatos, autenticação, paginação distintos) | "
    "Dados inconsistentes, falhas na exibição, custo alto de manutenção por integração | "
    "Pipeline ETL unificado com schema normalizado (NormalizedProduct) que abstrai diferenças |\n"
    "| P-02 | Latência na atualização de preços entre coleta e exibição | "
    "Usuário encontra preço divergente no checkout, gerando frustração e perda de confiança | "
    "Revalidação sob demanda via ISR com revalidate: 60 + webhook de invalidação por evento |\n"
    "| P-03 | Baixa indexação de conteúdo em SPAs tradicionais (React puro, Vue CSR) | "
    "Perda de até 70% do tráfego orgânico potencial (SEO) | "
    "Renderização híbrida (SSR + ISR) no Next.js 14 App Router |\n"
    "| P-04 | Carregamento lento em redes móveis brasileiras (3G/4G instável) | "
    "Taxa de rejeição superior a 53% quando LCP > 4s (dados Google) | "
    "Otimização de imagens via next/image (WebP/AVIF), Code Splitting automático |\n"
    "| P-05 | Ausência de histórico de preços em comparadores existentes | "
    "Consumidor não sabe se o preço atual é bom ou inflacionado | "
    "Snapshots diários de preço com gráfico de tendência dos últimos 90 dias |\n"
    "| P-06 | Links de afiliado quebrados ou sem rastreabilidade | "
    "Afiliados perdem comissão, plataforma perde receita | "
    "Sistema de redirecionamento com tracking de cliques, UTM automático e relatório de conversão |\n\n"
    "--- FIM DA REFERÊNCIA. Gere com este nível de profundidade para O PROJETO REAL. ---\n"
)
