EXEMPLAR_P03 = (
    "REFERÊNCIA DE PROFUNDIDADE (use como guia de densidade, NÃO copie):\n\n"
    "## Princípios Arquiteturais\n"
    "| Princípio | Descrição Concreta | Implicação Técnica | Decisão Arquitetural Crítica |\n"
    "|---|---|---|---|\n"
    "| ISR First | Toda página de produto é pré-renderizada estaticamente e regenerada em "
    "background a cada 60 segundos | Uso de revalidate: 60 em generateStaticParams do Next.js | "
    "REGRA: Nenhuma página pode usar force-dynamic. Teste verifica header x-nextjs-cache |\n"
    "| Normalização de Dados | Toda informação de produto passa por transformação para "
    "schema único antes de persistência | Camada de domínio (NormalizedProduct) com Pydantic | "
    "REGRA: Nenhum dado bruto de marketplace é exposto ao frontend |\n"
    "| Edge Caching | Conteúdo estático distribuído em PoPs próximos ao usuário | "
    "Deploy em Vercel Edge com Cache-Control: s-maxage=60, stale-while-revalidate=300 | "
    "REGRA: Toda resposta contém header x-vercel-cache. Teste verifica latência p95 < 200ms |\n"
    "| Fail Gracefully | Falha em um marketplace não impede exibição dos demais | "
    "Circuit breaker por collector com fallback para último cache válido | "
    "REGRA: Se Shopee estiver indisponível, página renderiza com dados dos demais |\n"
    "| Zero Trust em Scraping | Todo dado coletado é potencialmente malicioso | "
    "Sanitização HTML, validação de tipo, limites de tamanho | "
    "REGRA: Nenhum texto coletado renderizado sem DOMPurify |\n"
    "| Observabilidade Nativa | Todo componente emite métricas, logs e traces desde o dia 1 | "
    "OpenTelemetry SDK em Next.js e FastAPI, logs em JSON | "
    "REGRA: Todo request gera trace_id propagado end-to-end |\n\n"
    "## Diferenciais\n"
    "| Abordagem Atual | Problema | Como Este Sistema Supera |\n"
    "|---|---|---|\n"
    "| Scraping em tempo real (Buscapé) | Lentidão 3-8s por busca e bloqueio de IP | "
    "Cache ISR: dados pré-renderizados em <100ms; invalidação por webhook |\n"
    "| Renderização no Cliente (CSR) | SEO inexistente, primeira pintura >4s | "
    "SSR/ISR de 100% das páginas com LCP alvo <2.5s |\n"
    "| Comparação estática (blogs) | Dados desatualizados, sem personalização | "
    "Gráfico de histórico de 90 dias + alertas por email |\n"
    "| Agregadores sem rastreabilidade | Afiliados não rastreiam conversão | "
    "Links com UTM automático, dashboard de cliques por afiliado |\n\n"
    "--- FIM DA REFERÊNCIA ---\n"
)
