EXEMPLAR_P04 = (
    "REFERÊNCIA DE PROFUNDIDADE (use como guia de densidade, NÃO copie):\n\n"
    "## Requisitos Funcionais (Consolidados)\n"
    "| ID | Requisito | Critério de Aceite | Prioridade | Complexidade | Componente |\n"
    "|---|---|---|---|---|---|\n"
    "| RF-01 | Busca Unificada Multi-Loja | GET /api/v1/search?q=jbl+510bt retorna JSON com "
    "campo results[] contendo itens de >=2 marketplaces. Status 200. Tempo p95 < 1000ms | Must | Média | backend-api |\n"
    "| RF-02 | Página de Produto com ISR | URL /produto/{slug} retorna HTML com status 200. "
    "Header x-nextjs-cache presente. Revalidação a cada 60s | Must | Alta | frontend-nextjs |\n"
    "| RF-03 | Histórico de Preços | GET /api/v1/products/{slug}/history?days=90 retorna JSON "
    "com data_points[] contendo >=1 entry por semana nos últimos 90 dias | Should | Média | backend-api |\n"
    "| RF-04 | Alertas de Queda de Preço | POST /api/v1/alerts com body {email, product_slug, "
    "target_price} retorna 201. Quando preço <= target, email em <=5min | Should | Alta | backend-api |\n"
    "| RF-05 | Redirecionamento Affiliate | Clique em 'Ver Oferta' registra click em affiliate_clicks "
    "e abre URL com utm_source=omniprice em nova aba | Must | Baixa | frontend-nextjs |\n"
    "| RF-07 | Sitemap Dinâmico | GET /sitemap.xml retorna XML válido com todas URLs de produto. "
    "lastmod reflete updated_at | Must | Baixa | frontend-nextjs |\n"
    "| RF-08 | Filtragem por Marketplace | GET /api/v1/search?marketplace=amazon retorna apenas "
    "ofertas da Amazon. Dropdown de filtro funcional | Must | Baixa | backend-api |\n"
    "| RF-09 | Ordenação de Resultados | GET /api/v1/search?sort=price_asc retorna ordenado. "
    "Opções: price_asc, price_desc, rating_desc, relevance | Must | Baixa | backend-api |\n"
    "| RF-11 | Coleta Agendada | Celery Beat dispara tasks a cada 30min para todos os produtos "
    "ativos. Verificável via logs | Must | Média | collector-service |\n"
    "| RF-12 | Invalidação de Cache ISR | Após atualização de preço, webhook revalida página. "
    "Preço atualizado aparece em <=2min | Must | Média | collector-service |\n\n"
    "NOTA: Cada RF referencia o componente responsável. Critérios incluem endpoint, "
    "status HTTP e formato de resposta.\n\n"
    "--- FIM DA REFERÊNCIA ---\n"
)
