EXEMPLAR_P05 = (
    "REFERÊNCIA DE PROFUNDIDADE (use como guia de densidade, NÃO copie):\n\n"
    "## Requisitos Não-Funcionais\n"
    "| ID | Categoria | Requisito | Métrica | Target |\n"
    "|---|---|---|---|---|\n"
    "| RNF-01 | Performance | LCP em páginas de produto | Google Lighthouse p95 | <2.5s |\n"
    "| RNF-02 | Performance | First Input Delay (FID) | Google Lighthouse p95 | <100ms |\n"
    "| RNF-03 | Performance | Cumulative Layout Shift (CLS) | Google Lighthouse p95 | <0.1 |\n"
    "| RNF-04 | Performance | Tempo de resposta API busca | p95 via OpenTelemetry | <500ms |\n"
    "| RNF-05 | Performance | Tempo de resposta API produto | p95 via OpenTelemetry | <300ms |\n"
    "| RNF-06 | SEO | Indexabilidade de páginas de produto | Google Search Console | 100% válidos |\n"
    "| RNF-07 | SEO | Meta tags (title, description, canonical, og:*) | Teste Playwright | 100% |\n"
    "| RNF-08 | Disponibilidade | Uptime do frontend e API | UptimeRobot | >=99.9% |\n"
    "| RNF-09 | Escalabilidade | Concorrência frontend | Load test k6 | >=1000 req/s |\n"
    "| RNF-10 | Escalabilidade | Concorrência API | Load test k6 | >=500 req/s p95 <500ms |\n"
    "| RNF-11 | Segurança | Proteção XSS | OWASP ZAP scan | 0 vulnerabilidades |\n"
    "| RNF-12 | Segurança | Headers de segurança | SecurityHeaders.com | Nota A ou superior |\n"
    "| RNF-13 | Segurança | Dados sensíveis não expostos em logs | Auditoria manual | 0 ocorrências |\n"
    "| RNF-14 | Compatibilidade | Browsers suportados | Playwright cross-browser | Chrome 90+, Firefox 90+, Safari 15+ |\n"
    "| RNF-15 | Compatibilidade | Responsividade | Playwright 3 viewports | 375px, 768px, 1440px |\n"
    "| RNF-16 | Observabilidade | Logs estruturados JSON | Formato verificável | 100% dos serviços |\n"
    "| RNF-17 | Observabilidade | Traces distribuídos end-to-end | Presença de trace_id | 100% requests |\n"
    "| RNF-18 | Usabilidade | Tempo para completar busca | User testing | <=3 cliques |\n\n"
    "NOTA: 18 RNFs cobrindo 8 categorias, todos com target numérico verificável.\n\n"
    "--- FIM DA REFERÊNCIA ---\n"
)
