EXEMPLAR_P06 = (
    "REFERÊNCIA DE PROFUNDIDADE (use como guia de densidade, NÃO copie):\n\n"
    "## Arquitetura e Tech Stack\n"
    "- **Estilo:** Microserviços com Serverless Edge\n"
    "```mermaid\ngraph TB\n"
    "  USER[Usuário] -->|HTTPS| CDN[Vercel Edge/CDN]\n"
    "  CDN -->|ISR/SSR| NEXT[Next.js 14]\n"
    "  NEXT -->|REST| API[FastAPI]\n"
    "  API -->|Query| PG[(PostgreSQL 16)]\n"
    "  API -->|Cache| REDIS[(Redis 7.2)]\n"
    "  CELERY[Celery Workers] -->|Scrape| MP[Marketplaces]\n"
    "  CELERY -->|Persist| PG\n"
    "  API -->|Alerts| SMTP[SendGrid]\n"
    "  API -->|Errors| SENTRY[Sentry]\n"
    "```\n\n"
    "| Camada | Tecnologia | Versão | Justificativa | Alternativa Rejeitada |\n"
    "|---|---|---|---|---|\n"
    "| Frontend/Edge | Next.js 14 | 14.2.x | SSR/ISR nativo para SEO | Nuxt.js — menor ecossistema |\n"
    "| Backend API | FastAPI | 0.111.x | Async nativo, Pydantic | Flask — bloqueio async |\n"
    "| Data Store | PostgreSQL | 16.x | ACID, busca trigram pg_trgm | MongoDB — dados estruturados |\n"
    "| Cache | Redis | 7.2.x | In-memory, TTL, pub/sub | Memcached — sem persistência |\n"
    "| Scraping | Playwright | 1.44.x | Renderiza SPAs, async | Selenium — mais lento |\n"
    "| Workers | Celery | 5.4.x | Distribuído, retry, beat | APScheduler — single-process |\n\n"
    "## ADRs (Decisões Arquiteturais)\n"
    "Para cada decisão:\n"
    "| Campo | Valor |\n|---|---|\n"
    "| ID | ADR-01 |\n"
    "| Status | ACEITA |\n"
    "| Contexto | Páginas precisam de SEO forte e dados frescos |\n"
    "| Decisão | ISR com revalidate: 60 para todas as páginas /produto/[slug] |\n"
    "| Alternativas Rejeitadas | SSR puro — carga proporcional ao tráfego. "
    "CSR — SEO inexistente. SSG — rebuild inviável para milhares de produtos |\n"
    "| Consequências | (+) Latência <100ms cache hit. (+) SEO completo. (-) Até 60s de atraso |\n"
    "| Mitigação | Webhook de revalidação on-demand. Badge 'Atualizado há X min' |\n\n"
    "NOTA: 8 ADRs no padrão ouro, cada um com 7 campos. Mínimo 5 para o sistema.\n\n"
    "--- FIM DA REFERÊNCIA ---\n"
)
