EXEMPLAR_P06 = (
    "REFERÊNCIA DE FORMATO (use como guia de densidade, NÃO copie dados):\n\n"
    "## Arquitetura e Tech Stack\n"
    "- **Estilo:** [tipo de arquitetura]\n"
    "```mermaid\ngraph TB\n"
    "  COMP_A[Componente A] -->|protocolo| COMP_B[Componente B]\n"
    "  COMP_B -->|protocolo| COMP_C[(Banco de Dados)]\n"
    "```\n\n"
    "| Camada | Tecnologia | Versão | Justificativa | Alternativa Rejeitada |\n"
    "|---|---|---|---|---|\n"
    "| [camada] | [tech] | [versão exata] | [motivo] | [alternativa — motivo rejeição] |\n\n"
    "## ADRs (Decisões Arquiteturais)\n"
    "| Campo | Valor |\n|---|---|\n"
    "| ID | ADR-01 |\n"
    "| Decisão | [o que foi escolhido] |\n"
    "| Alternativa Rejeitada | [opção descartada com motivo] |\n"
    "| Consequências | [prós e contras] |\n"
    "| Mitigação | [como os contras são tratados] |\n\n"
    "REGRA: Mínimo 6 camadas na tech stack. Mínimo 5 ADRs no formato ficha.\n"
    "--- FIM DA REFERÊNCIA ---\n"
)
