EXEMPLAR_P07 = (
    "REFERÊNCIA DE PROFUNDIDADE (use como guia de densidade, NÃO copie):\n\n"
    "## Análise de Segurança\n"
    "| ID | Ameaça STRIDE | Componente | Severidade | Mitigação Concreta |\n"
    "|---|---|---|---|---|\n"
    "| SEC-01 | Spoofing — Requisições falsificadas | API Gateway | Alta | "
    "Rate limiting 60 req/min + JWT para endpoints protegidos. Middleware Edge + slowapi |\n"
    "| SEC-02 | Tampering — Manipulação de preços | Backend | Alta | "
    "Dados servidos read-only. Arquitetura unidirecional: Collectors → PG → API → Frontend |\n"
    "| SEC-03 | Information Disclosure — Credenciais em logs | API | Média | "
    "Filtro de log detecta patterns de API keys e substitui por ***REDACTED*** |\n"
    "| SEC-04 | DoS — Flood de requisições | Edge | Alta | "
    "Rate limiting em 3 camadas: Edge, Middleware Next.js, FastAPI @limiter |\n"
    "| SEC-05 | XSS — Injeção via títulos de produto | Frontend | Alta | "
    "DOMPurify.sanitize(title) + bleach no backend. Testes injetam <script>alert(1)</script> |\n"
    "| SEC-06 | SSRF — Collector redirecionado para rede interna | Collector | Média | "
    "Whitelist de domínios: apenas amazon.com.br, shopee.com.br, magazineluiza.com.br, mercadolivre.com.br |\n\n"
    "**Dados Sensíveis:**\n"
    "| Dado | Classificação | Criptografia | Retenção |\n"
    "|---|---|---|---|\n"
    "| Email do usuário | PII | AES-256 em repouso | Até exclusão ou 1 ano de inatividade |\n"
    "| IP do usuário (cliques) | PII | SHA-256 hash, nunca IP raw | 90 dias, depois anonimizado |\n"
    "| Credenciais de API | Secret | Variáveis de ambiente, nunca em código | Rotação trimestral |\n\n"
    "--- FIM DA REFERÊNCIA ---\n"
)
