EXEMPLAR_P08 = (
    "REFERÊNCIA DE PROFUNDIDADE (use como guia de densidade, NÃO copie):\n\n"
    "## Escopo MVP\n"
    "**O QUE ESTÁ NO MVP:**\n"
    "- RF-01 (Busca Unificada) — Core do produto, sem busca não há comparação\n"
    "- RF-02 (Página de Produto ISR) — Necessário para SEO e conversão\n"
    "- RF-05 (Redirecionamento Affiliate) — Fonte de receita principal\n"
    "- RF-07 (Sitemap) — Obrigatório para indexação Google\n"
    "- RF-08 (Filtragem por Marketplace) — Usabilidade mínima\n"
    "- RF-09 (Ordenação) — Usabilidade mínima\n"
    "- RF-11 (Coleta Agendada) — Sistema não funciona sem dados\n"
    "- RF-12 (Invalidação ISR) — Dados precisam estar atualizados\n\n"
    "**O QUE NÃO ESTÁ NO MVP:**\n"
    "- RF-03 (Histórico de Preços) — Requer >=7 dias de dados coletados. Incluir em v1.5\n"
    "- RF-04 (Alertas de Preço) — Requer integração SendGrid + JWT. Incluir em v1.5\n"
    "- RF-06 (Dashboard Admin) — Nice-to-have. Incluir em v1.1\n"
    "- App mobile nativo — PWA cobre 90% dos casos mobile com 1/5 do custo\n"
    "- Recomendação por IA — Requer histórico massivo não disponível no lançamento\n\n"
    "--- FIM DA REFERÊNCIA ---\n"
)
