EXEMPLAR_P09 = (
    "REFERÊNCIA DE PROFUNDIDADE (use como guia de density, NÃO copie):\n\n"
    "## Riscos Consolidados\n"
    "| # | Risco | Probabilidade | Impacto | Mitigação | Workaround Atual |\n"
    "|---|---|---|---|---|---|\n"
    "| R-01 | Marketplace altera layout HTML quebrando seletores CSS | Alta (~1x/mês) | Alto | "
    "Seletores versionados em config/selectors/. Alerta Sentry com screenshot | "
    "Cache stale serve dados antigos. SLA correção: 24h |\n"
    "| R-02 | Bloqueio de IP por anti-bot | Alta (Amazon e Shopee) | Médio | "
    "Proxy rotation pool >=20 IPs brasileiros. Delay 2-5s. User-Agent rotation | "
    "Coleta degrada mas não para. Cache stale ativo |\n"
    "| R-03 | API de marketplace deprecada ou breaking change | Média | Alto | "
    "Monitoramento de changelogs. Collector testa response schema | "
    "Fallback para scraping se API falhar |\n"
    "| R-04 | Custo de infraestrutura excede orçamento | Média | Médio | "
    "Budget alerts na Vercel e Railway. Auto-scaling com limites | "
    "Cache agressivo reduz requests ao backend |\n"
    "| R-05 | PostgreSQL atinge limite de armazenamento | Baixa | Alto | "
    "Monitoramento de disco. Task cleanup_stale_data | "
    "Upgrade para plano maior se necessário |\n"
    "| R-06 | Latência ISR causa preço desatualizado | Média | Médio | "
    "Badge 'Atualizado há X min'. Webhook on-demand | "
    "Disclaimer legal no footer |\n"
    "| R-07 | Vulnerabilidade XSS via título injetado | Baixa | Alto | "
    "Sanitização dupla: bleach + DOMPurify. Testes XSS automáticos | "
    "CSP header bloqueia inline scripts |\n"
    "| R-08 | Celery worker em crash loop | Baixa | Alto | "
    "Health check container. Docker restart on-failure:10 | "
    "Tasks idempotentes, re-execução segura |\n\n"
    "## Métricas de Sucesso\n"
    "| Métrica | Target | Como Medir |\n"
    "|---|---|---|\n"
    "| Lighthouse Performance | >=90 | npx lighthouse --output=json → categories.performance.score |\n"
    "| LCP (p95) | <2.5s | Google Search Console → Core Web Vitals |\n"
    "| Tempo API busca (p95) | <500ms | OpenTelemetry → http.route=/api/v1/search |\n"
    "| Uptime mensal | >=99.9% | UptimeRobot check a cada 1min |\n"
    "| Taxa sucesso coleta | >=90% | SELECT COUNT(*) FILTER (WHERE status='success') |\n"
    "| Páginas indexadas | 100% | Google Search Console → Válidas vs total slugs |\n"
    "| CTR afiliado | >=5% | clicks / page_views * 100 |\n"
    "| Cobertura testes backend | >=80% | pytest --cov → TOTAL |\n\n"
    "--- FIM DA REFERÊNCIA ---\n"
)
