EXEMPLAR_P10 = (
    "REFERÊNCIA DE PROFUNDIDADE (use como guia de densidade, NÃO copie):\n\n"
    "## Plano de Implementação\n"
    "| Fase | Duração | Entregas | Critério de Conclusão | Dependência |\n"
    "|---|---|---|---|---|\n"
    "| 1 — Infraestrutura | 2 semanas | PG schema, Redis, Docker Compose, seed, migrations | "
    "docker-compose up funciona; migrations rodam; seed popula 10 produtos | Nenhuma |\n"
    "| 2 — Backend API | 2 semanas | Endpoints REST, serviços, rate limiting, health check | "
    "Todos endpoints retornam respostas válidas; cobertura >=80%; pytest 0 falhas | Fase 1 |\n"
    "| 3 — Collectors | 3 semanas | 4 collectors, normalizers, Celery, proxy manager | "
    "Cada collector extrai preço de >=1 produto real; dados no PostgreSQL | Fase 2 |\n"
    "| 4 — Frontend | 3 semanas | Todas páginas, componentes, ISR, SEO | "
    "npm run build sem erros; Lighthouse >=90; E2E passam | Fase 2 |\n"
    "| 5 — Deploy | 2 semanas | Staging, CI/CD, segurança, observabilidade | "
    "Staging operacional; smoke test passa; OWASP ZAP limpo | Fases 1-4 |\n\n"
    "**Para cada fase, listar:**\n"
    "- Arquivos criados/modificados\n"
    "- Testes obrigatórios\n"
    "- Critério de aceite binário\n\n"
    "## Decisões do Debate\n"
    "| Round | Tipo | Decisão | Justificativa Técnica |\n"
    "|---|---|---|---|\n"
    "| R2 | ACEITO | Near Real-Time em vez de Real-Time | "
    "ISR não garante sincronia milissegundo; 5min é aceitável para comparação |\n"
    "| R3 | MELHORIA | Implementar stale-while-revalidate no Cache-Control | "
    "Garante disponibilidade durante regeneração ISR |\n\n"
    "--- FIM DA REFERÊNCIA ---\n"
)
