EXEMPLAR_P11 = (
    "REFERÊNCIA DE PROFUNDIDADE (use como guia de densidade, NÃO copie):\n\n"
    "## Constraints Técnicos\n"
    "- Linguagem: TypeScript 5.3 (Strict Mode) / Python 3.11\n"
    "- Framework: Next.js 14.2 (App Router) / FastAPI 0.111.x\n"
    "- Banco de dados: PostgreSQL 16 + Redis 7.2\n"
    "- Infraestrutura: Vercel (Frontend/Edge) + Railway (Backend/Workers)\n"
    "- Segurança: Rate Limiting 60 req/min, CSP Headers, HTTPS, JWT auth, LGPD compliance\n\n"
    "## Matriz de Rastreabilidade\n"
    "| RF-ID | Componente | Arquivo | Teste que Valida | Critério |\n"
    "|---|---|---|---|---|\n"
    "| RF-01 | backend-api | app/api/v1/routes/search.py | "
    "test_search.py::test_multi_marketplace | results[] com >=2 marketplaces, status 200 |\n"
    "| RF-02 | frontend-nextjs | app/produto/[slug]/page.tsx | "
    "test_product_page.spec.ts::test_isr | Header x-nextjs-cache = HIT ou STALE |\n"
    "| RF-05 | frontend + backend | OfferCard.tsx + clicks.py | "
    "test_affiliate_click.spec.ts | Click gera registro + nova aba com UTM |\n"
    "| RF-07 | frontend-nextjs | app/sitemap.ts | "
    "test_sitemap.spec.ts | XML válido com >=1 URL e lastmod |\n\n"
    "NOTA: Cada RF deve ter: componente, arquivo, teste específico e critério binário.\n\n"
    "## Limitações Conhecidas\n"
    "| ID | Limitação | Severidade | Impacto | Workaround Atual | Quando Resolvida |\n"
    "|---|---|---|---|---|---|\n"
    "| LIM-01 | Bloqueio de IP por anti-bot | Alta | Coleta falha temporariamente | "
    "Proxy rotation + backoff + cache stale serve dados por até 1h | v1.1 — Bright Data 100+ IPs |\n"
    "| LIM-02 | ISR atraso de até 60s | Média | Preço pode estar desatualizado | "
    "Badge 'Atualizado há X min' + webhook on-demand | v1.5 — SSE push real-time |\n"
    "| LIM-03 | Sem app nativo | Baixa | UX mobile limitada | "
    "PWA com manifest.json | Nunca — PWA é definitivo |\n"
    "| LIM-04 | Rate limiting de marketplace limita coleta | Média | Coleta lenta para >10k produtos | "
    "Priorização por visualizações | v2.0 — Coleta distribuída multi-worker |\n"
    "| LIM-05 | Busca sem sinônimos (pg_trgm) | Baixa | 'headphone' não encontra 'fone' | "
    "Usuário busca em português | v2.0 — Elasticsearch |\n"
    "| LIM-06 | Histórico só após >=7 dias | Baixa | Produtos novos sem gráfico | "
    "Mensagem 'Histórico em breve' | Auto-resolvido com operação |\n"
    "| LIM-07 | Seletores CSS frágeis (Magalu) | Alta | Layout muda sem aviso | "
    "Screenshots + alerta Sentry. Correção <24h | v1.1 — Investigar API Magalu |\n"
    "| LIM-08 | Sem multi-idioma | Baixa | Apenas pt-BR | "
    "Foco no mercado brasileiro | v3.0 — i18n LATAM |\n\n"
    "--- FIM DA REFERÊNCIA ---\n"
)
