EXEMPLAR_P11 = (
    "REFERÊNCIA DE FORMATO (use como guia de densidade, NÃO copie dados):\n\n"
    "## Constraints Técnicos\n"
    "- Linguagem: [valor com versão exata]\n"
    "- Framework: [valor com versão exata]\n"
    "- Banco de dados: [valor com versão]\n"
    "- Infraestrutura: [provedores]\n"
    "- Segurança: [medidas concretas]\n\n"
    "## Matriz de Rastreabilidade\n"
    "| RF-ID | Componente | Arquivo | Teste que Valida | Critério |\n"
    "|---|---|---|---|---|\n"
    "| RF-01 | [módulo] | [arquivo.py] | [test_file::test_name] | [critério binário] |\n\n"
    "## Limitações Conhecidas\n"
    "| ID | Limitação | Severidade | Impacto | Workaround Atual | Quando Resolvida |\n"
    "|---|---|---|---|---|---|\n"
    "| LIM-01 | [limitação] | Alta | [impacto] | [workaround concreto] | [versão: v1.1, v2.0, Nunca] |\n\n"
    "REGRA: Rastreabilidade COMPLETA — usar MESMOS RF-IDs da tabela de RFs. Mínimo 6 limitações.\n"
    "--- FIM DA REFERÊNCIA ---\n"
)
