EXEMPLAR_P12 = (
    "REFERÊNCIA DE FORMATO (use como guia de densidade, NÃO copie dados):\n\n"
    "## Guia de Replicação Resumido\n"
    "### 1. Pré-requisitos\n"
    "| Ferramenta | Versão Exata | Verificação |\n"
    "|---|---|---|\n"
    "| [ferramenta] | [versão] | [comando --version] |\n\n"
    "### 2. Instalação\n"
    "```bash\ngit clone [url]\ncd [projeto]\n[comandos de install]\n```\n\n"
    "### 3. Execução\n"
    "```bash\n[comando para rodar]\n```\n\n"
    "### 4. Verificação\n"
    "```bash\ncurl [url/health] # Esperado: {resposta}\n```\n\n"
    "## Cláusula de Integridade\n"
    "| Item | Status |\n"
    "|---|---|\n"
    "| Todos os RF-IDs do Escopo existem na tabela de RFs | ✓/✗ |\n"
    "| Todos os riscos HIGH possuem mitigação | ✓/✗ |\n\n"
    "REGRA: Guia com 6+ passos. Cláusula with 8+ itens verificados.\n"
    "--- FIM DA REFERÊNCIA ---\n"
)
