EXEMPLAR_P12 = (
    "REFERÊNCIA DE PROFUNDIDADE (use como guia de densidade, NÃO copie):\n\n"
    "## Guia de Replicação Resumido\n"
    "### 1. Pré-requisitos\n"
    "| Ferramenta | Versão Exata | Verificação |\n"
    "|---|---|---|\n"
    "| Node.js | 18.17+ (LTS) | node --version retorna v18.17.x |\n"
    "| Python | 3.11.x | python3 --version retorna 3.11.x |\n"
    "| Docker | 24.0+ | docker --version |\n"
    "| Docker Compose | 2.20+ (plugin v2) | docker compose version |\n\n"
    "### 2. Instalação\n"
    "```bash\n"
    "git clone https://github.com/empresa/projeto.git\n"
    "cd projeto\n"
    "cp .env.example .env\n"
    "npm install\n"
    "cd backend && pip install -e '.[dev]'\n"
    "```\n\n"
    "### 3. Infraestrutura\n"
    "```bash\n"
    "docker compose up -d postgres redis\n"
    "docker compose exec postgres pg_isready -U user  # Esperado: accepting connections\n"
    "docker compose exec redis redis-cli ping  # Esperado: PONG\n"
    "```\n\n"
    "### 4. Backend\n"
    "```bash\n"
    "cd backend && alembic upgrade head\n"
    "python ../scripts/seed_db.py\n"
    "uvicorn app.main:app --reload --port 8000\n"
    "curl http://localhost:8000/api/v1/health  # {status: healthy}\n"
    "```\n\n"
    "### 5. Frontend\n"
    "```bash\n"
    "npm run build && npm run dev  # http://localhost:3000\n"
    "```\n\n"
    "### 6. Verificação\n"
    "```bash\n"
    "curl -s http://localhost:3000/api/v1/health | jq .\n"
    "# Esperado: {\"status\": \"healthy\", \"database\": \"up\", \"cache\": \"up\"}\n"
    "```\n\n"
    "## Cláusula de Integridade\n"
    "| Item | Status |\n"
    "|---|---|\n"
    "| Todos os RF-IDs do Escopo existem na tabela de RFs | ✓/✗ |\n"
    "| Todos os riscos HIGH possuem mitigação | ✓/✗ |\n"
    "| Tech Stack consistente entre seções | ✓/✗ |\n"
    "| Métricas possuem target quantitativo | ✓/✗ |\n"
    "| Security Review endereça ameaças HIGH | ✓/✗ |\n"
    "| Nenhuma seção contém 'A DEFINIR' | ✓/✗ |\n"
    "| Matriz de Rastreabilidade cobre todos os RFs | ✓/✗ |\n"
    "| Diagramas Mermaid são renderizáveis | ✓/✗ |\n"
    "| Guia de replicação é autocontido | ✓/✗ |\n\n"
    "--- FIM DA REFERÊNCIA ---\n"
)
